name: CI/CD with Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-flask-demo:${{ github.sha }} .

    - name: Tag image as latest
      run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/app-flask-demo:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/app-flask-demo:latest

    - name: Push image with commit SHA
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-flask-demo:${{ github.sha }}

    - name: Push image with latest tag
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-flask-demo:latest

    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BASTION_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          ssh -o StrictHostKeyChecking=no ubuntu@192.168.122.54 '
            kubectl set image deployment/flask-demo flask-demo=${{ secrets.DOCKERHUB_USERNAME }}/app-flask-demo:${{ github.sha }} &&
            kubectl rollout status deployment/flask-demo
          '
